#!/usr/bin/env bash
# Changes hosts addresses for localhost and facebook

cp /etc/hosts ~/tmp_hosts
echo "127.0.0.2		localhost" > ~/tmp_hosts
echo "8.8.8.8		facebook.com" >> ~/tmp_hosts
cp -f ~/tmp_hosts /etc/hosts
